Tourist Website Added
ZeroOctave/ZeroOctave-Javascript-Projects pull request #735
Opened 2022-05-27 10:43 UTC by samipak458

### 🛠️ Fixes Issue #715 

### 👨‍💻 Changes proposed
Tourist Website Added

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

### 📷 Screenshots
![image](https://user-images.githubusercontent.com/52650290/170684791-0912b369-4a11-4435-8aed-5f7ebfc9c056.png)

2022-05-27 10:46 UTC, samipak458 commented
@Astrodevil kindly review my PR. Thank you.

2022-05-27 17:45 UTC, Astrodevil requested changes
Please move img and gif files from css to respective folder. Make required changes.

2022-05-27 17:46 UTC, Astrodevil commented on cards.json
> +        "name": "Tourist Website",
Please update cards.json alphabetically

2022-05-28 10:59 UTC, samipak458 commented on cards.json
> +        "name": "Tourist Website",
Done

2022-05-28 11:00 UTC, samipak458 commented
All the required has been made. Kindly review and merge my PR. Thank you.

2022-05-28 17:27 UTC, Astrodevil commented
You can create new PR properly.

2022-05-28 17:27 UTC, closed without merging

2022-05-29 09:20 UTC, samipak458 commented
@Astrodevil here the new PR link: https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/pull/756 kindly review it.