Country Guide
ZeroOctave/ZeroOctave-Javascript-Projects pull request #835
Opened 2022-08-10 14:50 UTC by AbhishekRP2002

### 🛠️ Fixes Issue (#806 )

### 👨‍💻 Changes proposed
This project displays a list of common information which includes Population , currency , Country capital , Continent about that country including an image of the country’s flag.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Decriptipon: Created a web app which displays a list of common information which includes Population , currency , Country capital , Continent about that country including an image of the country’s flag using RESTful API for fetching respective country data /information.
### 📷 Screenshots

![cntryguide](https://user-images.githubusercontent.com/86261428/183930033-4715dbf0-34d6-40b7-a4d5-e505cacceb34.png)

2022-08-11 01:51 UTC, myhacktech commented
@AbhishekRP2002 have u added a new webpage or exiting (then attach link)

2022-08-11 14:31 UTC, AbhishekRP2002 commented
I've added a new web page.

2022-08-11 15:01 UTC, myhacktech commented
> I've added a new web page.

ok great

2022-08-11 15:01 UTC, myhacktech submitted a review, later dismissed

2022-08-11 15:02 UTC, myhacktech commented
@Astrodevil to ber merged

2022-08-12 04:10 UTC, Astrodevil reviewed
Follow alphabetical order in cards.json. Also add project in README. Don't put .vscode and don't make changes in style.css

2022-08-28 12:43 UTC, Astrodevil commented
conflicts are there

2023-02-25 06:50 UTC, Anmol-Baranwal requested changes
Everything else working correctly !!

Please remove the .vscode folder then I will merge the PR.

2023-02-25 06:50 UTC, Anmol-Baranwal commented on .vscode/settings.json
> +}
Remove .vscode directory

2023-03-18 18:15 UTC, closed without merging