Custom Video Player
ZeroOctave/ZeroOctave-Javascript-Projects pull request #842
Opened 2022-08-15 06:09 UTC by tarunbisht-24

### 🛠️ Fixes Issue #828 

### 👨‍💻 Changes proposed

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

This is a Custom Video Player which is built in HTML, CSS, and JS. There are many things you can do with this custom video player like skipping the video at any point, forward 10s and backward 10s, playing pause at any instant, etc.

### 📷 Screenshots

![Uploading 183439757-69188fc4-65f4-42f4-ab2e-5fe7d3c0759e.jpeg…]()

2022-08-19 06:15 UTC, myhacktech commented
> ### 🛠️ Fixes Issue #828
> ### 👨‍💻 Changes proposed
> ### ✅ Check List (Check all the applicable boxes)
> * [x]  My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
> * [x]  This PR does not contain plagiarized content.
> * [x]  My Addition/Changes works properly and matches the overall repo pattern.
> * [x]  The title of my pull request is a short description of the requested changes.
> 
> ### 📄 Note to reviewers
> This is a Custom Video Player which is built in HTML, CSS, and JS. There are many things you can do with this custom video player like skipping the video at any point, forward 10s and backward 10s, playing pause at any instant, etc.
> 
> ### 📷 Screenshots
> ![183439757-69188fc4-65f4-42f4-ab2e-5fe7d3c0759e](https://user-images.githubusercontent.com/77788209/184585110-f2b041e2-692a-4c2d-aab4-d3aca528e2ce.jpeg)

can u attach a screen recording of ur work,as its not clear to understand ur changes

2022-08-19 14:31 UTC, tarunbisht-24 commented
https://user-images.githubusercontent.com/77788209/185640249-17ad288b-aa95-4348-9019-22de9129d955.mp4

The first slider is for volume increase and decrease I've turned on the volume but the sound didn't get enabled while recording

2022-08-19 16:47 UTC, myhacktech approved these changes

2022-08-19 16:47 UTC, myhacktech commented
@Astrodevil plz chk ,if its alright..

2022-08-29 14:50 UTC, Astrodevil commented
squash commits

2023-02-25 07:21 UTC, Anmol-Baranwal requested changes
> It is preferred to work on different branches for different projects. 

- Still, add the custom video player project in cards.json.
- Add both projects [here](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects#available-projects)
- `Change` the video location from the `meditation` directory in the Video directory with an appropriate name.
- And the changes requested.
- It will also be good if the video is of better quality, even if it is of less duration.

2023-02-25 07:21 UTC, Anmol-Baranwal commented on cards.json
> +        "link": "Public/geolocation.html"
add video player project as well in cards.json

2023-02-25 07:21 UTC, Anmol-Baranwal commented on Public/customvideoplayer.html
> +        <video class="player__video viewer" src="652333414.mp4"></video>
- correct the file path

2023-02-25 07:21 UTC, Anmol-Baranwal commented on Public/customvideoplayer.html
> +    <link rel="stylesheet" href="customvideoplayer.css">
- specify the correct file path.

2023-02-25 07:21 UTC, Anmol-Baranwal commented on Public/customvideoplayer.html
> +    <script src="customvideoplayer.js"></script>
```suggestion
    <script src="../assets/Js/customvideoplayer.js"></script>
```
- This will be the correct file path, change others accordingly.

2023-02-25 07:21 UTC, Anmol-Baranwal commented on Public/geolocation.html
> +  <link rel="stylesheet" href="geolocation.css">
- specify the correct file path.

2023-02-25 07:21 UTC, Anmol-Baranwal commented on Public/geolocation.html
> +  <script src="geolocation.js"></script>
- specify the correct file path.

2023-03-09 12:44 UTC, Astrodevil commented
@tarunbisht-24  To much commits If you want to still make change Please create a new clean PR by taking suggestion from this.

2023-03-09 12:44 UTC, closed without merging