Changing the UI of height converter
ZeroOctave/ZeroOctave-Javascript-Projects pull request #893
Opened 2022-09-25 10:02 UTC by Drishti-jain21

### 🛠️ Fixes Issue (Number) #887 

### 👨‍💻 Changes proposed
I changed the background image, improved the UI of form and added text message when height is converted
It even has a reset button, which was not there earlier.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/100796147/192138030-be27bdd5-7a93-4ffc-aff5-ac409051634f.png">

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

2022-09-25 16:39 UTC, myhacktech approved these changes
@Astrodevil

2022-09-27 09:39 UTC, Astrodevil commented
Not working properly
![1](https://user-images.githubusercontent.com/73425223/192491929-dd7caa17-5f62-40df-9698-50ef1238d594.png)

2022-09-27 10:12 UTC, Drishti-jain21 commented
It is working fine on my system, I just checked

2022-09-27 16:19 UTC, Drishti-jain21 commented
![image](https://user-images.githubusercontent.com/100796147/192580414-9e0e2f44-a5a4-47ad-99f1-8d569feec095.png)

![image](https://user-images.githubusercontent.com/100796147/192580465-504850ff-4c0c-4efa-85ac-02941ac700e3.png)

![image](https://user-images.githubusercontent.com/100796147/192580493-197abccc-f2f4-4f47-b754-d438d7defee3.png)

2023-02-24 08:27 UTC, Anmol-Baranwal requested changes
Please make these changes, then it would work properly.

2023-02-24 08:27 UTC, Anmol-Baranwal commented on Public/height-converter.html
> +<body style="background-image: url('/assets/Images/heightconverter.jpg');">
```suggestion
<body style="background-image: url('../assets/Images/heightconverter.jpg');">
```

2023-02-24 08:27 UTC, Anmol-Baranwal commented on Public/height-converter.html
> +    <link rel="stylesheet" href="/assets/css/height-converter.css">
```suggestion
    <link rel="stylesheet" href="../assets/css/height-converter.css">
```

2023-02-24 08:30 UTC, Anmol-Baranwal commented
@Astrodevil 

I prefer the previous UI as it was simple and present image has no appropriate styling and doesn't really signifies anything. 
Still, I would merge the PR if the above changes are done.

2023-03-27 19:25 UTC, closed without merging